version: '3'

services:
  server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./firmware:/firmware
      - /dev/ttyUSB0:/dev/ttyUSB0
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
